# Generated by Django 4.2.2 on 2023-07-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.IntegerField()),
                ('nombres', models.CharField(default='', max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mi_tabla_usuario',
            },
        ),
        migrations.CreateModel(
            name='create_new_consultas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rut', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('Correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='create_new_consultas_respondidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=70)),
                ('rut', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('Correo', models.CharField(max_length=100)),
                ('fecha_respuesta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='create_nuevo_card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_card', models.ImageField(blank=True, null=True, upload_to='img/carta')),
                ('nombre_card', models.CharField(max_length=25)),
                ('cargo_card', models.CharField(max_length=100)),
                ('descrip_card', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='create_nuevo_curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('img_curso', models.ImageField(blank=True, null=True, upload_to='img/cursos')),
                ('form_carga_curso', models.FileField(blank=True, null=True, upload_to='documents')),
                ('descrip_corta_curso', models.CharField(max_length=250)),
                ('descrip_larga_curso', models.CharField(max_length=600)),
                ('requisitos_curso', models.CharField(max_length=100)),
                ('time_start_curso', models.DateField()),
                ('time_end_curso', models.DateField()),
                ('servicio_curso', models.CharField(max_length=100)),
                ('hospital_curso', models.CharField(max_length=100)),
                ('personal_cursos', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='create_nuevo_publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_pub', models.ImageField(blank=True, null=True, upload_to='img/public')),
                ('nombre_pub', models.CharField(max_length=100)),
                ('descrip_pub', models.CharField(default='SOME STRING', max_length=100)),
                ('is_curso', models.BooleanField(default=False)),
                ('is_curso_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='new_class_hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hospital', models.CharField(max_length=70)),
            ],
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('myapp', 'new_class_hospital').objects.bulk_create([
                apps.get_model('myapp', 'new_class_hospital')(nombre_hospital='Hospital las Higueras'),
                apps.get_model('myapp', 'new_class_hospital')(nombre_hospital='Hospital Clínico Regional Dr. Guillermo Grant Benavente'),
                apps.get_model('myapp', 'new_class_hospital')(nombre_hospital='Hospital San Agustin de Florida'),
                apps.get_model('myapp', 'new_class_hospital')(nombre_hospital='Hospital Santa Juana'),
                # Agrega más hospitales si es necesario
            ]),
        ),
        migrations.CreateModel(
            name='new_class_servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sev', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('myapp', 'new_class_servicio').objects.bulk_create([
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Servicio de emergencias'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Medicina interna'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Pediatría'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Cirugía'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Ginecología y obstetricia'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Cardiología'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Neurología'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Oncología'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Ortopedia'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Psiquiatría'),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Urología '),
                apps.get_model('myapp', 'new_class_servicio')(nombre_sev='Maternidad '),

                # Agrega más hospitales si es necesario
            ]),
        ),
    ]
