# Generated by Django 4.2.2 on 2023-07-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_nuevo_publicacion',
            name='is_curso_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
